import type { BookRule, StageGuide, TemporaryCondition } from "./domain";

export const BOOK_EDITION = "삐뽀삐뽀 119 이유식, 2023 최신개정판";
export const RECOMMENDATION_VERSION = "pp119-complete-v2";

export const stageGuides: StageGuide[] = [
  {
    stage: "initial",
    label: "초기",
    ageMonths: [6, 6],
    milkMlRange: [500, 900],
    mealRange: [1, 3],
    snackRange: [0, 0],
    offerGramsRange: [30, 100],
    meatGramsPerDay: [10, 20],
    textureMmRange: [1, 3],
    textureDescription: "수프 정도에서 시작해 대충 갈거나 으깬 작은 입자로 빠르게 진행",
    grainDescription: "10~8배죽에서 시작해 7~5배죽까지 진행",
    newFoodIntervalDays: [3, 3],
    servingModes: ["섞은 죽", "토핑", "익숙한 재료와 분리 제공"],
    developmentGoals: ["숟가락 경험", "혀로 밀어내지 않고 삼키기", "다양한 맛과 냄새 경험"],
    sourcePages: ["책 p.24-29", "책 p.64-69", "책 p.302-314"],
  },
  {
    stage: "middle",
    label: "중기",
    ageMonths: [7, 8],
    milkMlRange: [500, 800],
    mealRange: [2, 3],
    snackRange: [1, 2],
    offerGramsRange: [70, 120],
    meatGramsPerDay: [10, 20],
    textureMmRange: [3, 5],
    textureDescription: "연두부처럼 부드럽고 최소 3mm 이상의 입자",
    grainDescription: "7배죽에서 5배죽, 잘 먹으면 3배죽",
    newFoodIntervalDays: [2, 3],
    servingModes: ["토핑", "반찬 분리", "핑거푸드 병행"],
    developmentGoals: ["핑거푸드 잡기", "숟가락 쥐기", "컵으로 물 마시기"],
    sourcePages: ["책 p.24-29", "책 p.138-145", "책 p.315-325"],
  },
  {
    stage: "late",
    label: "후기",
    ageMonths: [9, 11],
    milkMlRange: [500, 700],
    mealRange: [3, 3],
    snackRange: [2, 3],
    offerGramsRange: [120, 150],
    meatGramsPerDay: [20, 30],
    textureMmRange: [5, 7],
    textureDescription: "잘 익은 바나나 정도로 부드럽고 최소 5~7mm 입자",
    grainDescription: "3배죽에서 2배죽·무른밥·진밥으로 진행",
    newFoodIntervalDays: [2, 3],
    servingModes: ["밥과 반찬", "식판", "핑거푸드", "덮밥"],
    developmentGoals: ["하루 세 끼 리듬", "매 끼 숟가락 연습", "분리된 음식 선택"],
    sourcePages: ["책 p.24-29", "책 p.180-185", "책 p.326-336"],
  },
  {
    stage: "completion",
    label: "완료기",
    ageMonths: [12, 18],
    milkMlRange: [400, 500],
    mealRange: [3, 3],
    snackRange: [2, 3],
    offerGramsRange: [120, 180],
    meatGramsPerDay: [30, 40],
    textureMmRange: [7, 10],
    textureDescription: "부드러운 진밥·완자 정도에서 7~10mm 이상으로 진행",
    grainDescription: "2배죽·진밥에서 일반 밥과 가족식의 부드러운 변형으로 진행",
    newFoodIntervalDays: [2, 3],
    servingModes: ["밥과 반찬", "가족식 변형", "식판", "스스로 먹기"],
    developmentGoals: ["가족과 세 끼", "컵 사용", "도움받아 스스로 먹기"],
    sourcePages: ["책 p.24-29", "책 p.230-235", "책 p.337-349"],
  },
];

export const bookRules: BookRule[] = [
  {
    id: "start_at_six_months_with_readiness",
    layer: "introduction",
    strength: "repeatedExplicit",
    title: "만 6개월과 준비 신호를 함께 확인",
    description: "월령만으로 자동 시작하지 않고 혀 내밀기 반사, 머리 가누기, 도움받아 앉기, 음식 관심을 함께 본다.",
    sourcePages: ["책 p.12-15", "책 p.282-288", "책 p.302-305"],
    overridableBy: "clinician",
  },
  {
    id: "introduction_order",
    layer: "introduction",
    strength: "repeatedExplicit",
    title: "다섯 식품군 도입 순서",
    description: "쌀·오트밀, 고기, 이파리 채소, 노란 채소, 과일 순으로 식품군을 빠르게 확보하고 기존 재료에 누적한다.",
    sourcePages: ["책 p.13-17", "책 p.64-69", "책 p.287-310"],
  },
  {
    id: "single_new_food_slot",
    layer: "introduction",
    strength: "direct",
    title: "새 재료는 기본 한 가지",
    description: "초기에는 원인 추적이 가능하도록 한 번에 새 재료 하나를 소량 도입한다.",
    sourcePages: ["책 p.14-17", "책 p.64-69", "책 p.307-318"],
  },
  {
    id: "new_food_interval",
    layer: "introduction",
    strength: "direct",
    title: "단계별 관찰 간격",
    description: "초기 기본 3일, 8개월 이후 2~3일을 기본값으로 사용하고 반응이나 의료진 지시에 따라 늘린다.",
    sourcePages: ["책 p.24-29", "책 p.64-69", "책 p.307-318"],
    overridableBy: "clinician",
  },
  {
    id: "daily_meat",
    layer: "nutrition",
    strength: "repeatedExplicit",
    title: "고기는 매일",
    description: "살코기 자체를 매일 제공하고 단계별 하루 목표량을 추적한다. 육수만으로 대체하지 않는다.",
    sourcePages: ["책 p.16-17", "책 p.24-39", "책 p.315-356"],
  },
  {
    id: "fish_weekly_cap",
    layer: "nutrition",
    strength: "repeatedExplicit",
    title: "생선은 주 2회 이하",
    description: "가시·껍질을 제거해 완전히 익히고 최근 7일 제공 횟수가 2회를 넘지 않게 한다.",
    sourcePages: ["책 p.32-37", "책 p.180-185", "책 p.345-350"],
    overridableBy: "clinician",
  },
  {
    id: "five_food_groups",
    layer: "nutrition",
    strength: "repeatedExplicit",
    title: "하루 전체의 식품군 균형",
    description: "곡류, 고기·단백질, 이파리 채소, 노란 채소, 과일을 한 끼가 아닌 하루 전체에서 확인한다.",
    sourcePages: ["책 p.13-17", "책 p.64-69", "책 p.294-318"],
  },
  {
    id: "texture_progression",
    layer: "texture",
    strength: "repeatedExplicit",
    title: "미음에 머무르지 않기",
    description: "양보다 아기가 안전하게 다룰 수 있는 최대 질감을 우선하고, 단계의 최소 입자보다 오래 묽게 유지하지 않는다.",
    sourcePages: ["책 p.20-25", "책 p.43-44", "책 p.294-337"],
  },
  {
    id: "finger_food_by_middle",
    layer: "texture",
    strength: "direct",
    title: "7~8개월까지 핑거푸드 시작",
    description: "손으로 잡기 쉽고 잇몸으로 으깨지는 안전한 형태로 손-입 협응과 자기 먹기를 연습한다.",
    sourcePages: ["책 p.20-23", "책 p.138-145", "책 p.315-325"],
  },
  {
    id: "no_honey_before_one",
    layer: "safety",
    strength: "hard",
    title: "돌 전 꿀 금지",
    description: "가열 여부와 관계없이 만 12개월 전에는 꿀을 제공하지 않는다.",
    sourcePages: ["책 p.18-19", "책 p.32-39"],
    overridableBy: "never",
  },
  {
    id: "no_milk_drink_before_one",
    layer: "safety",
    strength: "hard",
    title: "돌 전 생우유 음료 금지",
    description: "조리에 넣어 완전히 익히는 용도와 음료 제공을 구분하며, 음료는 만 12개월 이후로 제한한다.",
    sourcePages: ["책 p.32-39", "책 p.344-352"],
    overridableBy: "clinician",
  },
  {
    id: "fully_cook_animal_food",
    layer: "safety",
    strength: "hard",
    title: "계란·고기·생선 완전 가열",
    description: "날것이나 덜 익힌 형태를 제외하고 속까지 완전히 익힌다.",
    sourcePages: ["책 p.18-19", "책 p.32-41"],
    overridableBy: "never",
  },
  {
    id: "choking_forms_blocked",
    layer: "safety",
    strength: "hard",
    title: "질식 위험 형태 제외",
    description: "통견과류, 통포도, 끈적한 떡, 큰 소시지·고기 덩어리 등은 후보에서 제거한다.",
    sourcePages: ["책 p.18-19", "책 p.224-230", "책 p.350-365"],
    overridableBy: "never",
  },
  {
    id: "no_added_salt",
    layer: "nutrition",
    strength: "repeatedExplicit",
    title: "두 돌까지 가능한 무염",
    description: "소금·간장·된장·김치와 첨가당을 기본 추천에서 제외하고 재료 본연의 맛을 경험하게 한다.",
    sourcePages: ["책 p.34-41", "책 p.286-301", "책 p.330-350"],
  },
  {
    id: "parent_child_roles",
    layer: "behavior",
    strength: "repeatedExplicit",
    title: "부모와 아기의 역할 분리",
    description: "부모는 무엇을 언제 어디서 줄지 정하고, 아기는 제공된 음식 중 무엇을 얼마나 먹을지 결정한다.",
    sourcePages: ["책 p.276-279", "책 p.292-293", "책 p.337-348"],
  },
  {
    id: "repeat_refused_food",
    layer: "behavior",
    strength: "direct",
    title: "거부는 반복 노출",
    description: "단순 거부는 알레르기와 분리하며 익숙한 음식 옆에 소량을 두고 조리법과 질감을 바꾸어 반복 경험한다.",
    sourcePages: ["책 p.287-293", "책 p.307-318", "책 p.337-348"],
  },
  {
    id: "store_safely",
    layer: "storage",
    strength: "direct",
    title: "냉장·냉동과 재냉동 제한",
    description: "1회분으로 소분하고 일반 이유식은 냉장 1~2일, 냉동 1~2주 안에 사용하며 해동한 음식은 재냉동하지 않는다.",
    sourcePages: ["책 p.36-37", "책 p.48-61"],
  },
  {
    id: "suspected_reaction_pause",
    layer: "condition",
    strength: "hard",
    title: "의심 반응 재료 자동 재추천 금지",
    description: "해당 재료를 중단하고 시간·양·조리 형태·증상을 기록한다. 기존에 문제없던 음식은 일괄 중단하지 않는다.",
    sourcePages: ["책 p.364-373"],
    overridableBy: "clinician",
  },
];

export const conditionGuidance: Record<Exclude<TemporaryCondition, "none">, {
  title: string;
  recommendation: string;
  avoid: string[];
  sourcePages: string[];
}> = {
  cold: {
    title: "감기 중",
    recommendation: "평소 식품군을 유지하되 수분이 있고 소화하기 쉬운 형태로 소량 제공해요.",
    avoid: ["강요해서 먹이기", "회복 전 무리한 질감 상향"],
    sourcePages: ["책 p.374-375"],
  },
  diarrhea: {
    title: "설사 중",
    recommendation: "수분을 우선하고 급성기 이후 가능한 빨리 기존 식단으로 돌아가요.",
    avoid: ["지나치게 달거나 기름진 음식", "과일주스", "묽은 흰쌀죽만 장기간 제공"],
    sourcePages: ["책 p.376-377"],
  },
  constipation: {
    title: "변비 경향",
    recommendation: "수분과 섬유질을 함께 보고 배·자두·콩·브로콜리·양배추·고구마 같은 후보를 우선해요.",
    avoid: ["유제품 과다", "흰쌀밥만 반복", "덜 익은 바나나"],
    sourcePages: ["책 p.378-379"],
  },
  mouthPain: {
    title: "입안이 아픈 상태",
    recommendation: "체온 정도 또는 시원하고 부드러우며 자극 적은 형태로 수분과 영양을 제공해요.",
    avoid: ["뜨거운 음식", "산미가 강한 음식", "거친 질감"],
    sourcePages: ["책 p.380-381"],
  },
};

export const absoluteRestrictions = [
  { id: "honey", label: "꿀", minimumAgeMonths: 12, reason: "돌 전 보툴리즘 위험", sourcePages: ["책 p.18-19", "책 p.35"] },
  { id: "milk-drink", label: "생우유 음료", minimumAgeMonths: 12, reason: "돌 전 음료 제공 제한", sourcePages: ["책 p.32-39"] },
  { id: "raw-egg", label: "날계란·반숙 계란", minimumAgeMonths: 999, reason: "완전 가열 필요", sourcePages: ["책 p.18-19", "책 p.34"] },
  { id: "raw-meat-fish", label: "날고기·날생선", minimumAgeMonths: 999, reason: "완전 가열 필요", sourcePages: ["책 p.18-19"] },
  { id: "whole-nuts", label: "통견과류", minimumAgeMonths: 48, reason: "질식 위험", sourcePages: ["책 p.32-37", "책 p.350-365"] },
  { id: "whole-grape", label: "통포도", minimumAgeMonths: 48, reason: "질식 위험 형태", sourcePages: ["책 p.350-365"] },
];

export function getStageGuide(stage: Exclude<StageGuide["stage"], never>) {
  return stageGuides.find((guide) => guide.stage === stage) ?? stageGuides[0];
}
