import type {
  BabyProfile,
  ChildIngredientState,
  IngredientDefinition,
  MealHistoryEntry,
} from "./domain";

export const demoProfile: BabyProfile = {
  id: "demo-child",
  nickname: "우리 아기",
  stage: "prestart",
  ageMonths: 4,
  mealsPerDay: 1,
  preferredMealTime: "10:00",
  textureMm: 0,
  preparationStyle: "cube",
};

export const ingredientDefinitions: IngredientDefinition[] = [
  {
    id: "rice",
    name: "쌀",
    emoji: "🍚",
    category: "grain",
    introductionGroup: "grain",
    minimumStage: "initial",
    introductionPriority: 1,
  },
  {
    id: "oatmeal",
    name: "오트밀",
    emoji: "🌾",
    category: "grain",
    introductionGroup: "grain",
    minimumStage: "initial",
    introductionPriority: 2,
  },
  {
    id: "beef",
    name: "소고기",
    emoji: "🥩",
    category: "meat",
    introductionGroup: "meat",
    minimumStage: "initial",
    introductionPriority: 3,
  },
  {
    id: "cabbage",
    name: "양배추",
    emoji: "🥬",
    category: "vegetable",
    introductionGroup: "leafy",
    minimumStage: "initial",
    introductionPriority: 4,
  },
  {
    id: "bokchoy",
    name: "청경채",
    emoji: "🌿",
    category: "vegetable",
    introductionGroup: "leafy",
    minimumStage: "initial",
    introductionPriority: 5,
  },
  {
    id: "pumpkin",
    name: "단호박",
    emoji: "🎃",
    category: "vegetable",
    introductionGroup: "yellow",
    minimumStage: "initial",
    introductionPriority: 6,
  },
  {
    id: "zucchini",
    name: "애호박",
    emoji: "🥒",
    category: "vegetable",
    introductionGroup: "yellow",
    minimumStage: "initial",
    introductionPriority: 7,
  },
  {
    id: "apple",
    name: "사과",
    emoji: "🍎",
    category: "fruit",
    introductionGroup: "fruit",
    minimumStage: "initial",
    introductionPriority: 8,
  },
  {
    id: "pork",
    name: "돼지고기",
    emoji: "",
    category: "meat",
    introductionGroup: "meat",
    minimumStage: "initial",
    introductionPriority: 9,
  },
  {
    id: "chicken",
    name: "닭고기",
    emoji: "",
    category: "meat",
    introductionGroup: "meat",
    minimumStage: "initial",
    introductionPriority: 10,
  },
  {
    id: "broccoli",
    name: "브로콜리",
    emoji: "",
    category: "vegetable",
    introductionGroup: "leafy",
    minimumStage: "initial",
    introductionPriority: 11,
  },
  {
    id: "carrot",
    name: "당근",
    emoji: "",
    category: "vegetable",
    introductionGroup: "yellow",
    minimumStage: "initial",
    introductionPriority: 12,
  },
  {
    id: "sweet-potato",
    name: "고구마",
    emoji: "",
    category: "vegetable",
    introductionGroup: "yellow",
    minimumStage: "initial",
    introductionPriority: 13,
  },
  {
    id: "whitefish",
    name: "흰살생선",
    emoji: "",
    category: "fish",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 14,
  },
  {
    id: "egg",
    name: "완숙 계란",
    emoji: "",
    category: "egg",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 15,
  },
  {
    id: "tofu",
    name: "두부",
    emoji: "",
    category: "beans",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 16,
  },
  {
    id: "legumes",
    name: "콩류",
    emoji: "",
    category: "beans",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 17,
  },
  {
    id: "kelp",
    name: "다시마",
    emoji: "",
    category: "seaweed",
    introductionGroup: "other",
    minimumStage: "middle",
    introductionPriority: 18,
  },
  {
    id: "yogurt",
    name: "플레인 요구르트",
    emoji: "",
    category: "dairy",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 19,
  },
  {
    id: "peanut-butter",
    name: "땅콩버터",
    emoji: "",
    category: "nutsOil",
    introductionGroup: "other",
    minimumStage: "initial",
    introductionPriority: 20,
  },
];

export const demoIngredientStates: ChildIngredientState[] = [
  {
    ingredientId: "rice",
    status: "testing",
    testDay: 1,
    exposureCount: 0,
    lastOfferedAt: null,
  },
  {
    ingredientId: "oatmeal",
    status: "ready",
    testDay: null,
    exposureCount: 0,
    lastOfferedAt: null,
  },
];

export const demoHistory: MealHistoryEntry[] = [];
